GET http://127.0.0.1:8000/api/posts HTTP/1.1

###
POST http://127.0.0.1:8000/api/posts HTTP/1.1
content-type: application/json

{
    "title": "My 10th Model",
    "content": "This my third title which i hate so much"
}

###

PUT http://127.0.0.1:8000/api/posts/update/4 HTTP/1.1
content-type: application/json

{
    "title": "My 4th Model yup",
    "content": "This my u[p] title which i hate so much"
} 

###
DELETE  http://127.0.0.1:8000/api/posts/delete/10 HTTP/1.1
 